# HEVD appveyor configuration

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: 3.0.{build}

# branches to build
branches:
  # whitelist
  only:
  - master

# Do not build on tags (GitHub and BitBucket)
skip_tags: true

# Do not build feature branch with open Pull Requests
# skip_branch_with_pr: true

# Maximum number of concurrent jobs for the project
max_jobs: 1

#---------------------------------#
#    environment configuration    #
#---------------------------------#

# Build worker image (VM template)
image:
  - Visual Studio 2017
  - Ubuntu

# fetch repository as zip archive
# default is "false"
shallow_clone: true

# set clone depth
# clone entire repository history if not defined
clone_depth: 1

# this is how to allow failing jobs in the matrix
# environment:
#   matrix:
#   - job_name: Build HEVD for Windows
#   - job_name: Build HEVD for Linux
#     job_depends_on: Build HEVD for Windows
#   - job_name: Package HEVD
#     job_depends_on: Build HEVD for Linux

matrix:
  fast_finish: true

for:
  - matrix:
      only:
        - image: Visual Studio 2017
    clone_folder: c:\projects\hevd
    build_script:
      - cmd: cd c:\projects\hevd\Builder
      - cmd: Build_HEVD_All.bat
    after_build:
      - cmd: 7z a c:\projects\hevd\HEVD.zip c:\projects\hevd\build\*
  
  - matrix:
      only:
        - image: Ubuntu
    clone_folder: /home/appveyor/projects/hevd
    build_script:
      - sh: cd /home/appveyor/projects/hevd/Builder
      - sh: sh Build_HEVD_All.sh
    after_build:
      - sh: 7z a /home/appveyor/projects/hevd/HEVD.zip /home/appveyor/projects/hevd/build/*

# disable test
test: off

# artifacts
artifacts:
  - path: HEVD.zip

# disable deployment
deploy: off


# remote desktop debugging
# environment:
#   APPVEYOR_RDP_PASSWORD: Passw0rd!

# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
